#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : cpu_block.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Dec 03 17:58:29 IST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: cpu_block.sh [-help]
# usage: cpu_block.sh [-lib_map_path]
# usage: cpu_block.sh [-noclean_files]
# usage: cpu_block.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'cpu_block.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_chip2chip_v5_0_5 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_5 zynq_ultra_ps_e_vip_v1_0_5 gtwizard_ultrascale_v1_7_6 fifo_generator_v13_2_4 util_vector_logic_v2_0_1 axi_bram_ctrl_v4_1_1 blk_mem_gen_v8_4_3 xlconstant_v1_1_6 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 axi_protocol_converter_v2_1_19 axi_clock_converter_v2_1_18 axi_dwidth_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "cpu_block.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_chip2chip_v5_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/9d55/hdl/axi_chip2chip_v5_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_axi_chip2chip_0_0/sim/cpu_block_axi_chip2chip_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_proc_sys_reset_0_0/sim/cpu_block_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim/cpu_block_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/sim/cpu_block_aurora_64b66b_0_1_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/sim/cpu_block_aurora_64b66b_0_1_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/sim/cpu_block_aurora_64b66b_0_1_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/sim/cpu_block_aurora_64b66b_0_1_gt.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_1/sim/cpu_block_aurora_64b66b_0_1_fifo_gen_master.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_aurora_lane.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_support.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_support_reset_logic.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_ultrascale_tx_userclk.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_clock_module.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/example_design/gt/cpu_block_aurora_64b66b_0_1_multi_wrapper.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/example_design/gt/cpu_block_aurora_64b66b_0_1_ultrascale_rx_userclk.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_standard_cc_module.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_reset_logic.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_cdc_sync.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1_core.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_axi_to_ll.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_block_sync_sm.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_common_reset_cbcc.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_common_logic_cbcc.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_cbcc_gtx_6466.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_channel_err_detect.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_channel_init_sm.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_ch_bond_code_gen.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_64b66b_descrambler.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_err_detect.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_global_logic.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_polarity_check.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/example_design/gt/cpu_block_aurora_64b66b_0_1_wrapper.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_lane_init_sm.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_ll_to_axi.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_rx_stream_datapath.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_rx_stream.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_width_conversion.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_64b66b_scrambler.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_sym_dec.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_sym_gen.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_tx_stream_control_sm.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_tx_stream_datapath.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1/src/cpu_block_aurora_64b66b_0_1_tx_stream.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_clk_wiz_0_0/cpu_block_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_clk_wiz_0_0/cpu_block_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_util_vector_logic_0_0/sim/cpu_block_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_1 $vhdlan_opts \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/70bf/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_axi_bram_ctrl_0_0/sim/cpu_block_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c001/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_blk_mem_gen_0_0/sim/cpu_block_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_gpio_split_0_0/sim/cpu_block_gpio_split_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_util_ds_buf_0_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_util_ds_buf_0_0/sim/cpu_block_util_ds_buf_0_0.vhd" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_util_ds_buf_0_1/sim/cpu_block_util_ds_buf_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_xlconstant_0_0/sim/cpu_block_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_dsync_0_0/sim/cpu_block_dsync_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_axi_bram_ctrl_1_0/sim/cpu_block_axi_bram_ctrl_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_xlconstant_1_0/sim/cpu_block_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_xbar_0/sim/cpu_block_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ac9d/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/e578/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ipshared/c923" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../emtf_elm2_2019.1.srcs/sources_1/bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_auto_us_0/sim/cpu_block_auto_us_0.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_auto_ds_0/sim/cpu_block_auto_ds_0.v" \
    "$ref_dir/../../../bd/cpu_block/ip/cpu_block_auto_ds_1/sim/cpu_block_auto_ds_1.v" \
    "$ref_dir/../../../bd/cpu_block/sim/cpu_block.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.cpu_block xil_defaultlib.glbl -o cpu_block_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./cpu_block_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./cpu_block.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/ehep/Vivado_Projects/ELM_ALEX_project/emtf_elm2_2019.1/emtf_elm2_2019.1.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key cpu_block_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc cpu_block_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./cpu_block.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: cpu_block.sh [-help]\n\
Usage: cpu_block.sh [-lib_map_path]\n\
Usage: cpu_block.sh [-reset_run]\n\
Usage: cpu_block.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
