# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/emtf_elm1.xdc

# Block Designs: bd/cpu_block/cpu_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block || ORIG_REF_NAME==cpu_block} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_axi_chip2chip_0_0/cpu_block_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_axi_chip2chip_0_0 || ORIG_REF_NAME==cpu_block_axi_chip2chip_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_axi_interconnect_0_0/cpu_block_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_axi_interconnect_0_0 || ORIG_REF_NAME==cpu_block_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_proc_sys_reset_0_0/cpu_block_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_proc_sys_reset_0_0 || ORIG_REF_NAME==cpu_block_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/cpu_block_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==cpu_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1 || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/cpu_block_aurora_64b66b_0_1_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1_gt || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1_gt} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_1/cpu_block_aurora_64b66b_0_1_fifo_gen_master.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1_fifo_gen_master || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1_fifo_gen_master} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_clk_wiz_0_0/cpu_block_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_clk_wiz_0_0 || ORIG_REF_NAME==cpu_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_util_vector_logic_0_0/cpu_block_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_util_vector_logic_0_0 || ORIG_REF_NAME==cpu_block_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_axi_bram_ctrl_0_0/cpu_block_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_axi_bram_ctrl_0_0 || ORIG_REF_NAME==cpu_block_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_blk_mem_gen_0_0/cpu_block_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_blk_mem_gen_0_0 || ORIG_REF_NAME==cpu_block_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_gpio_split_0_0/cpu_block_gpio_split_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_gpio_split_0_0 || ORIG_REF_NAME==cpu_block_gpio_split_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_util_ds_buf_0_0/cpu_block_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_util_ds_buf_0_0 || ORIG_REF_NAME==cpu_block_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_util_ds_buf_0_1/cpu_block_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_util_ds_buf_0_1 || ORIG_REF_NAME==cpu_block_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_xlconstant_0_0/cpu_block_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_xlconstant_0_0 || ORIG_REF_NAME==cpu_block_xlconstant_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_dsync_0_0/cpu_block_dsync_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_dsync_0_0 || ORIG_REF_NAME==cpu_block_dsync_0_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_axi_bram_ctrl_1_0/cpu_block_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_axi_bram_ctrl_1_0 || ORIG_REF_NAME==cpu_block_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_xlconstant_1_0/cpu_block_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_xlconstant_1_0 || ORIG_REF_NAME==cpu_block_xlconstant_1_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_xbar_0/cpu_block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_xbar_0 || ORIG_REF_NAME==cpu_block_xbar_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_auto_us_0/cpu_block_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_auto_us_0 || ORIG_REF_NAME==cpu_block_auto_us_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_auto_ds_0/cpu_block_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_auto_ds_0 || ORIG_REF_NAME==cpu_block_auto_ds_0} -quiet] -quiet

# IP: bd/cpu_block/ip/cpu_block_auto_ds_1/cpu_block_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_block_auto_ds_1 || ORIG_REF_NAME==cpu_block_auto_ds_1} -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_axi_chip2chip_0_0/cpu_block_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_axi_chip2chip_0_0 || ORIG_REF_NAME==cpu_block_axi_chip2chip_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_axi_chip2chip_0_0/cpu_block_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_axi_chip2chip_0_0 || ORIG_REF_NAME==cpu_block_axi_chip2chip_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_proc_sys_reset_0_0/cpu_block_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_proc_sys_reset_0_0 || ORIG_REF_NAME==cpu_block_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_proc_sys_reset_0_0/cpu_block_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_proc_sys_reset_0_0 || ORIG_REF_NAME==cpu_block_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/cpu_block_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_zynq_ultra_ps_e_0_0/cpu_block_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==cpu_block_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/synth/cpu_block_aurora_64b66b_0_1_gt_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_0/synth/cpu_block_aurora_64b66b_0_1_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1_gt || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_1/cpu_block_aurora_64b66b_0_1_fifo_gen_master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1_fifo_gen_master || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/ip_1/cpu_block_aurora_64b66b_0_1_fifo_gen_master_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1_fifo_gen_master || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1 || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_aurora_64b66b_0_1/cpu_block_aurora_64b66b_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_aurora_64b66b_0_1 || ORIG_REF_NAME==cpu_block_aurora_64b66b_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_clk_wiz_0_0/cpu_block_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_clk_wiz_0_0 || ORIG_REF_NAME==cpu_block_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_clk_wiz_0_0/cpu_block_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_clk_wiz_0_0 || ORIG_REF_NAME==cpu_block_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_clk_wiz_0_0/cpu_block_clk_wiz_0_0_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_blk_mem_gen_0_0/cpu_block_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_util_ds_buf_0_0/cpu_block_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_util_ds_buf_0_0 || ORIG_REF_NAME==cpu_block_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_util_ds_buf_0_0/cpu_block_util_ds_buf_0_0_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_util_ds_buf_0_1/cpu_block_util_ds_buf_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_util_ds_buf_0_1 || ORIG_REF_NAME==cpu_block_util_ds_buf_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_util_ds_buf_0_1/cpu_block_util_ds_buf_0_1_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_auto_us_0/cpu_block_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_auto_us_0 || ORIG_REF_NAME==cpu_block_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_auto_us_0/cpu_block_auto_us_0_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_auto_ds_0/cpu_block_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_auto_ds_0 || ORIG_REF_NAME==cpu_block_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_auto_ds_0/cpu_block_auto_ds_0_ooc.xdc

# XDC: bd/cpu_block/ip/cpu_block_auto_ds_1/cpu_block_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cpu_block_auto_ds_1 || ORIG_REF_NAME==cpu_block_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cpu_block/ip/cpu_block_auto_ds_1/cpu_block_auto_ds_1_ooc.xdc

# XDC: bd/cpu_block/cpu_block_ooc.xdc
